const questions = [
  { sentence: '___ madre es profesora.', translation: 'My mother is a teacher.', hint: 'my', answer: 'Mi', choices: ['Mi', 'Mis', 'Tu', 'Sus', 'Tus'], explanation: 'Mi means “my” before one noun: madre (mother).' },
  { sentence: '___ libros están en la mesa.', translation: 'My books are on the table.', hint: 'my', answer: 'Mis', choices: ['Mi', 'Mis', 'Tus', 'Su', 'Tu'], explanation: 'Mis means “my” before a plural noun: libros (books).' },
  { sentence: '___ perro es pequeño.', translation: 'Your dog is small.', hint: 'your (one friend)', answer: 'Tu', choices: ['Tu', 'Tus', 'Mi', 'Sus', 'Mis'], explanation: 'Tu means “your” when speaking to one friend. Perro (dog) is singular.' },
  { sentence: '___ zapatos son negros.', translation: 'Your shoes are black.', hint: 'your (one friend)', answer: 'Tus', choices: ['Tu', 'Tus', 'Su', 'Mis', 'Mi'], explanation: 'Tus means “your” before a plural noun: zapatos (shoes).' },
  { sentence: '___ casa es blanca.', translation: 'Her house is white.', hint: 'her', answer: 'Su', choices: ['Su', 'Sus', 'Mi', 'Tus', 'Mis'], explanation: 'Su means “her” here. Use the singular form because casa (house) is singular.' },
  { sentence: '___ hermanos estudian español.', translation: 'His brothers study Spanish.', hint: 'his', answer: 'Sus', choices: ['Su', 'Sus', 'Tu', 'Mi', 'Mis'], explanation: 'Sus means “his” here. It is plural because hermanos (brothers) is plural.' },
  { sentence: '___ abuelo vive en México.', translation: 'Our grandfather lives in Mexico.', hint: 'our', answer: 'Nuestro', choices: ['Nuestro', 'Nuestra', 'Nuestros', 'Nuestras', 'Su'], explanation: 'Nuestro agrees with abuelo (grandfather): masculine and singular.' },
  { sentence: '___ hermana tiene diez años.', translation: 'Our sister is ten years old.', hint: 'our', answer: 'Nuestra', choices: ['Nuestro', 'Nuestra', 'Nuestros', 'Nuestras', 'Su'], explanation: 'Nuestra agrees with hermana (sister): feminine and singular.' },
  { sentence: '___ amigos comen pizza.', translation: 'Our friends eat pizza.', hint: 'our', answer: 'Nuestros', choices: ['Nuestro', 'Nuestra', 'Nuestros', 'Nuestras', 'Su'], explanation: 'Nuestros agrees with amigos (friends): masculine and plural.' },
  { sentence: '___ mochilas están aquí.', translation: 'Our backpacks are here.', hint: 'our', answer: 'Nuestras', choices: ['Nuestro', 'Nuestra', 'Nuestros', 'Nuestras', 'Su'], explanation: 'Nuestras agrees with mochilas (backpacks): feminine and plural.' }
];
